language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq devscripts libwww-perl
    - uscan --force-download
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get install -qq debhelper devscripts apache2-dev autotools-dev

script:
    - debuild -uc -us

#notifications:
#  email: false
