language: c

before_install:
    # update package list
    - sudo apt-get update -qq
    # installneeded packages for uscan
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    # download original tarball
    - uscan --force-download
    # remove packages needed for uscan
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    # pull build deps from debian/control
    - sudo mk-build-deps -ir
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

script:
    # build the debian package
    - debuild -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc
#notifications:
#  email: false
