language: c

before_install:
    # update package list
    - sudo apt-get update -qq
    # installneeded packages for uscan
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    # download original tarball
    - uscan --force-download
    # remove packages needed for uscan
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq

install:
    # install build dependencies
    - sudo apt-get install -qq --no-install-recommends debhelper devscripts apache2-dev autotools-dev

script:
    # build the debian package
    - debuild -uc -us

#notifications:
#  email: false
